version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - grib-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - grib-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: grib-{{ checksum "package.json" }}

      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
      docker:
        - image: circleci/node:latest-browsers
      steps:
        - run: npm --version
        - checkout
        - attach_workspace:
            at: .
        - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run: git config --global user.email "djabry@gmail.com"
        - run: git config --global user.name "CI"
        - run: npm run deploy

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master